# 服务器基本配置
server:
  port: 8080

# spring 基本配置
spring:
  # thymeleaf配置
  thymeleaf:
    cache: false
    suffix: .html
    mode: HTML5
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    data-password: 123456

#mybatis 数据库配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml